export type SymbolCategory = {
  slug: string;
  label: string;
  title: string;
  description: string;
  keyword: string;
  intro: string;
  about: string;
  symbols: string[];
};

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    slug: "down-arrow",
    label: "Down Arrow",
    keyword: "down arrow symbol",
    title: "Down Arrow Symbol – Copy & Paste ↓ ⬇ ⇓",
    description: "Down arrow symbols to copy and paste — single, double-headed, dashed, curved, and decorative variants.",
    intro: "A grid of every down arrow Unicode covers — single, double-headed, with stroke, with hook, dashed, zigzag, decorative. Click any tile to copy.",
    about: "Down arrows are everywhere — UI affordances, instructions, music notation, math, and chat shorthand for 'see below.' The Unicode standard packs them across several blocks (Arrows U+2190–U+21FF, Supplemental Arrows-A U+27F0–U+27FF, Supplemental Arrows-B U+2900–U+297F, Arrows for Mathematical Notation, and a few stragglers in Misc Symbols and Pictographs).",
    symbols: ["↓","⬇","⇓","⇣","⇊","⤓","⤋","⥥","⇩","↡","⭣","⮇","⮋","⮟","⮣","⇂","↧","↯","⇃","⤈","⤌","⤍","⤐","⤡","⥯","⥨","⭭","⮈","🔽","⏷","⏬","⮯","⇂","⥏","⥗","↓"],
  },
  {
    slug: "up-arrow",
    label: "Up Arrow",
    keyword: "up arrow symbol",
    title: "Up Arrow Symbol – Copy & Paste ↑ ⬆ ⇑",
    description: "Up arrow symbols to copy and paste — single, double-headed, with stroke, curved, and decorative variants.",
    intro: "Every up arrow Unicode supports — minimal, bold, decorative, with hooks and strokes. Click a tile to copy.",
    about: "Up arrows show direction, growth, return-to-top buttons, and music articulations. Unicode covers them across the Arrows, Supplemental Arrows, and Miscellaneous Symbols blocks.",
    symbols: ["↑","⬆","⇑","↟","⇈","⤊","⤒","⥉","⇪","⬈","⬉","⮉","⮝","⮙","🔼","⏶","⏫","🔝","⮬","⮨","⮊","⮟","⇧","⇡","⤉","⤴","⥌","⥏","⥔","⥘","⥐","⥃","⥑"],
  },
  {
    slug: "left-arrow",
    label: "Left Arrow",
    keyword: "left arrow symbol",
    title: "Left Arrow Symbol – Copy & Paste ← ⬅ ⇐",
    description: "Left arrow symbols to copy and paste — back, return, undo, and decorative left arrows.",
    intro: "Left-pointing arrows for navigation, return, undo, and prose. Click a tile to copy.",
    about: "Left arrows mostly signal 'back,' 'undo,' or 'previous.' They sit alongside their right-arrow counterparts in the Unicode arrow blocks.",
    symbols: ["←","⬅","⇐","⇇","⇚","⇍","↞","↤","↩","↫","⇦","⬱","⮐","⮈","⤺","⥄","⥆","⥒","⥖","⥚","⥢","⫷","◀","⫸","🔙","⮌","⮎","⮜","⇐","⇽","⟵","⟸","⟻","⤆"],
  },
  {
    slug: "right-arrow",
    label: "Right Arrow",
    keyword: "right arrow symbol",
    title: "Right Arrow Symbol – Copy & Paste → ➡ ⇒",
    description: "Right arrow symbols to copy and paste — next, forward, redo, and decorative right arrows.",
    intro: "Right-pointing arrows for navigation, forward, redo, and prose. Click a tile to copy.",
    about: "Right arrows are the most-used arrow in modern UI — Next, Forward, Continue. Unicode covers heavy, dashed, double-headed, and decorative variants.",
    symbols: ["→","➡","⇒","➔","➜","➝","➞","➟","➠","➢","➣","➤","➥","➦","➧","➨","➩","➪","➫","➬","➭","➮","➯","➱","➲","➳","➵","➶","➷","➸","➹","➺","➻","➼","➽","➾","⇨","⇉","↣","↦","↬","⤳","⤑","⥤"],
  },
  {
    slug: "heart",
    label: "Heart",
    keyword: "heart symbol",
    title: "Heart Symbol – Copy & Paste ♥ ❤ ♡",
    description: "Heart symbols and emoji to copy and paste — filled, outlined, decorative, and colored hearts.",
    intro: "Filled, outlined, ornate, and arrow-pierced hearts. Click a tile to copy.",
    about: "Hearts appear in five Unicode locations: Misc Symbols (♥, ♡), Dingbats (❤, ❥, ❦, ❧), Emoji presentation (♥️), Misc Symbols and Pictographs (💔–💟), and a few in the Supplemental Symbols block.",
    symbols: ["♥","❤","♡","❥","❦","❧","♥️","💖","💗","💓","💕","💘","💝","💞","💟","💌","💔","🫀","♥︎","💜","💛","💚","💙","🧡","🖤","🤍","🤎","❣️","💗","ღ","ɞ","ღ","꯭","ʚɞ"],
  },
  {
    slug: "star",
    label: "Star",
    keyword: "star symbol",
    title: "Star Symbol – Copy & Paste ★ ☆ ✦",
    description: "Star symbols, sparkles, and decorative stars to copy and paste.",
    intro: "Filled and outlined stars, sparkles, and dingbat stars. Click a tile to copy.",
    about: "Stars live across Misc Symbols (★, ☆), Dingbats (✦, ✧, ✩, ✪, ✫, ✬, ✭, ✮, ✯, ✰, ✱, ✲, ✳, ✴, ✵, ✶, ✷, ✸, ✹), and Emoji blocks.",
    symbols: ["★","☆","✦","✧","✩","✪","✫","✬","✭","✮","✯","✰","✱","✲","✳","✴","✵","✶","✷","✸","✹","⭐","🌟","✨","💫","⚝","⋆","✯","✪","✫","⭑","⭒","☪","☫","✠"],
  },
  {
    slug: "sun",
    label: "Sun",
    keyword: "sun symbol",
    title: "Sun Symbol – Copy & Paste ☀ ☼ ⛅",
    description: "Sun symbols, weather icons, and decorative suns to copy and paste.",
    intro: "Sun glyphs from minimal line icons to full emoji. Click a tile to copy.",
    about: "Sun symbols sit in Misc Symbols (☀, ☼, ☉), Misc Symbols and Pictographs (🌞, 🌝, 🌛, 🌜), and the Emoji blocks.",
    symbols: ["☀","☼","☉","☽","☾","☆","🌞","🌝","🌛","🌜","🌚","🌕","🌖","🌗","🌘","🌑","🌒","🌓","🌔","🌙","⛅","🌤","🌥","🌦","☁","☂","⚡","❄","☔","⛈"],
  },
  {
    slug: "moon",
    label: "Moon",
    keyword: "moon symbol",
    title: "Moon Symbol – Copy & Paste ☽ ☾ 🌙",
    description: "Moon symbols, crescents, and lunar phases to copy and paste.",
    intro: "Crescent moons, full moons, phases, and decorative lunar glyphs. Click any tile to copy.",
    about: "Moons appear in Misc Symbols (☽, ☾) and the full set of phase emoji (🌑–🌘) in the Misc Symbols and Pictographs block.",
    symbols: ["☽","☾","🌙","🌚","🌛","🌜","🌝","🌑","🌒","🌓","🌔","🌕","🌖","🌗","🌘","☪","ʚɞ","꒰ᐢ.   .ᐢ꒱","⊹","✩","☆","☄","✦","✧","⊙","◐","◑","◒","◓","◔","◕","○","●"],
  },
  {
    slug: "music",
    label: "Music",
    keyword: "music symbol",
    title: "Music Symbol – Copy & Paste ♪ ♫ ♬",
    description: "Music note symbols, clefs, rests, and decorative musical glyphs to copy and paste.",
    intro: "Notes, beamed eighths, sixteenths, sharps, flats, clefs, and rests. Click any tile to copy.",
    about: "Music symbols are concentrated in the Miscellaneous Symbols block (♩–♯) and the Musical Symbols block (U+1D100–U+1D1FF) for a much larger set including clefs, dynamics, and articulations.",
    symbols: ["♩","♪","♫","♬","♭","♮","♯","𝄞","𝄢","𝄡","𝄐","𝄑","𝄒","𝄓","𝄔","𝄕","𝄖","𝄗","𝄘","𝄙","𝄚","𝄛","𝄝","𝄞","𝄟","𝄠","𝄡","𝅗𝅥","𝅘𝅥","𝅘𝅥𝅮","𝅘𝅥𝅯","🎵","🎶","🎼","🎹","🎷","🎸","🎺","🎻","🥁"],
  },
  {
    slug: "check-mark",
    label: "Check Mark",
    keyword: "check mark symbol",
    title: "Check Mark Symbol – Copy & Paste ✓ ✔ ☑",
    description: "Check mark and tick symbols to copy and paste — light, heavy, and boxed.",
    intro: "Check marks for to-do lists, confirmation, and decoration. Click any tile to copy.",
    about: "Check marks sit in the Dingbats block (✓, ✔, ✗, ✘) and a few related ranges. Boxed and circled variants come from Enclosed Alphanumerics.",
    symbols: ["✓","✔","☑","✅","✗","✘","☒","❌","❎","☓","✕","✖","☐","◯","⊘","✚","✜","➕","➖","✦","✰","✩","☆","⚐","⚑","⚠","ℹ","✱","✲","✳","✴"],
  },
  {
    slug: "cross",
    label: "Cross",
    keyword: "cross symbol",
    title: "Cross Symbol – Copy & Paste † ✝ ☦",
    description: "Cross and religious symbols to copy and paste — Latin cross, Orthodox, Celtic, and decorative.",
    intro: "Latin crosses, Orthodox crosses, daggers, and decorative cross glyphs. Click any tile to copy.",
    about: "Crosses sit across Misc Symbols (✝, ☦, ☩, ☪) and Dingbats (✚, ✜, ✛, ✠). Daggers (†, ‡) live in General Punctuation.",
    symbols: ["†","‡","✝","☦","☧","☨","☩","✚","✛","✜","✠","✟","☫","☬","☭","♰","♱","✞","卐","卍","𓋹","☥","✚","➕","➖","✗","✘","☒","✕","✖"],
  },
  {
    slug: "currency",
    label: "Currency",
    keyword: "currency symbol",
    title: "Currency Symbol – Copy & Paste $ € ¥ £ ₹",
    description: "Currency symbols from every major country to copy and paste — dollar, euro, yen, pound, rupee, won, and more.",
    intro: "Every currency symbol Unicode supports — major and minor. Click any tile to copy.",
    about: "Most currency symbols live in the Currency Symbols block (U+20A0–U+20CF), with a few stragglers (the dollar sign, yen, pound) inherited from earlier encodings in Basic Latin and Latin-1 Supplement.",
    symbols: ["$","€","¥","£","₹","₽","₩","₪","₫","₴","₸","₺","₼","₾","₿","¢","ƒ","৳","฿","Kč","zł","kr","R$","₣","₤","₥","₦","₧","₨","₪","₯","₠","₡","₢","₣","₤","₥","₦","₧","₨","₩","₪","₫"],
  },
  {
    slug: "infinity",
    label: "Infinity",
    keyword: "infinity symbol",
    title: "Infinity Symbol – Copy & Paste ∞",
    description: "Infinity symbols and related glyphs to copy and paste.",
    intro: "Infinity, lemniscate, and related math glyphs. Click any tile to copy.",
    about: "The classic infinity (∞) is U+221E in the Mathematical Operators block. Tilted, incomplete, and decorated infinities are in Supplemental Mathematical Operators.",
    symbols: ["∞","♾","⧜","⧝","⧞","∝","∺","≎","≏","≍","∾","⋈","⩂","⋘","⋙","∮","∯","∰","∱","∲","∳","◌","○","◯","◎","☯"],
  },
  {
    slug: "bullet",
    label: "Bullet",
    keyword: "bullet point symbol",
    title: "Bullet Point Symbol – Copy & Paste • ◦ ▪",
    description: "Bullet point symbols and list markers to copy and paste.",
    intro: "Bullets in every shape and size for lists, captions, and decoration. Click any tile to copy.",
    about: "Bullets are scattered across General Punctuation (•, ‣), Geometric Shapes (▪, ▫, ●, ○, ◦), Miscellaneous Symbols, and Dingbats.",
    symbols: ["•","◦","▪","▫","●","○","◉","◎","◍","◐","◑","◒","◓","◔","◕","◖","◗","◘","◙","◚","◛","◜","◝","◞","◟","◠","◡","◢","◣","◤","◥","◦","‣","⁃","⁌","⁍","⁕","⁖","⁘","⁙","⁚","⁛","⁜"],
  },
  {
    slug: "triangle",
    label: "Triangle",
    keyword: "triangle symbol",
    title: "Triangle Symbol – Copy & Paste ▲ ▼ ◆",
    description: "Triangle symbols pointing every direction, filled and outlined, to copy and paste.",
    intro: "Up, down, left, right triangles in solid and outlined variants. Click any tile to copy.",
    about: "Triangles cluster in the Geometric Shapes block (U+25A0–U+25FF) with filled, outlined, small, and pointing variants in every cardinal direction.",
    symbols: ["▲","▼","◀","▶","△","▽","◁","▷","▴","▾","◂","▸","▵","▿","◃","▹","⏶","⏷","⏴","⏵","⊿","◬","◭","◮","◸","◹","◺","◿","▰","▱","◇","◆","◈"],
  },
  {
    slug: "crown",
    label: "Crown",
    keyword: "crown symbol",
    title: "Crown Symbol – Copy & Paste ♛ ♕ 👑",
    description: "Crown symbols — king, queen, royal, and decorative — to copy and paste.",
    intro: "Royal crowns, chess king/queen, and decorative tiara glyphs. Click any tile to copy.",
    about: "Chess crowns (♔–♛) live in Misc Symbols. The emoji crown (👑) is in Misc Symbols and Pictographs. A few decorative variants live in Supplemental Symbols and Pictographs.",
    symbols: ["♔","♕","♖","♗","♘","♙","♚","♛","♜","♝","♞","♟","👑","👸","🤴","🏰","🎩","🎓","ヅ","☥","✪","✯","✰","♚︎","♛︎","ෆ"],
  },
];

export const SYMBOL_BY_SLUG: Record<string, SymbolCategory> = Object.fromEntries(
  SYMBOL_CATEGORIES.map((c) => [c.slug, c])
);
